### ISSUE TITLE
Forked to keep up to date

### ISSUE THREAD

**Issue by DarkIsDude** [chriswayg/tor-server#1]
I all, I have forked this repo to keep it up to date, https://hub.docker.com/r/doudou34/tor-server/.

Thanks @chriswayg for your amazing taff!

**Comment by dmp1ce** [comment]
@DarkIsDude  Can you open up issues on your repository? How often are you updating your Tor version on your image?

**Comment by DarkIsDude** [comment]
@dmp1ce I try every two month. Done for issue, I will update it now

**Comment by DarkIsDude** [comment]
If you will use, I can update it every month ;). Let me know

**Comment by chriswayg** [comment]
@DarkIsDude nice to see, that you updated my previous version to be functional again! The more Tor servers the better! 

I finally updated my Tor server to Debian 9 stretch, which should auto-update on Docker Hub more reliably, as it is not built from source, but using the Tor repositories with recent builds.

**Comment by chriswayg** [comment]
### The latest Tor-Server Docker builds are working and ready for action!

https://hub.docker.com/r/chriswayg/tor-server/

**Comment by DarkIsDude** [comment]
Thanks a lot for your work. I can close this issue.
